# Generated by Django 4.0.5 on 2022-07-31 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('bio', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('batch', models.CharField(choices=[('user', None), ('Dr', 'Doctor'), ('Psk', 'psikolog'), ('Dt', 'dentist'), ('Dyt', 'diyetisyen')], default=None, max_length=5)),
                ('profile_avatar', models.ImageField(blank=True, upload_to='media/avatar')),
                ('background_image', models.ImageField(blank=True, upload_to='media/background')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('phone_number', models.BigIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserRoomMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_room_on', models.DateTimeField(auto_now_add=True)),
                ('left_room_on', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_room', to='store.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_of_room', to='users.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='followed', to='users.userprofile')),
                ('follower', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='users.userprofile')),
            ],
        ),
    ]
