# Generated by Django 4.0.5 on 2022-06-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_post_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hashtag',
            field=models.ManyToManyField(through='store.PostHashtag', to='store.hashtag'),
        ),
    ]
